/* Quiet discoveries in the shared sky. Destination submissions use their own shared store. */
(() => {
 const t=(en,es)=>document.documentElement.lang==='es'?es:en;
 const satellite=document.querySelector('.globe-gps-footer .satellite');
 if(!satellite)return;
 const moon=document.createElement('button');moon.type='button';moon.className='after-dark-moon';moon.setAttribute('aria-haspopup','dialog');moon.setAttribute('aria-controls','lost-after-dark');
 moon.innerHTML='<svg viewBox="0 0 100 100" aria-hidden="true"><defs><radialGradient id="after-dark-moon-gold" cx="43%" cy="45%" r="65%"><stop stop-color="#fffbc0"/><stop offset=".48" stop-color="#fff18a"/><stop offset=".8" stop-color="#f8d541"/><stop offset="1" stop-color="#dcae29"/></radialGradient><filter id="moon-painted-grain" x="0" y="0" width="100%" height="100%"><feTurbulence type="fractalNoise" baseFrequency=".22" numOctaves="3" seed="12" result="grain"/><feColorMatrix in="grain" type="saturate" values="0"/><feComponentTransfer><feFuncA type="linear" slope=".17"/></feComponentTransfer><feBlend in="SourceGraphic" mode="multiply"/><feComposite in2="SourceGraphic" operator="in"/></filter></defs><path d="M72 7C30-4 2 23 6 59C10 89 43 105 72 91C83 86 92 77 92 73C91 71 88 72 85 74C52 90 23 66 32 36C38 17 53 12 70 12C76 12 76 8 72 7Z" fill="url(#after-dark-moon-gold)" filter="url(#moon-painted-grain)"/></svg>';
 const moonSection=satellite.closest('.discover-section');
 satellite.closest('.globe-gps-footer').append(moon);
 function modal(id){const d=document.createElement('dialog');d.id=id;d.className='orbit-secret-dialog';document.body.append(d);d.addEventListener('click',e=>{if(e.target!==d)return;const r=d.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)d.close();});return d;}
 const dark=modal('lost-after-dark');dark.setAttribute('aria-labelledby','after-dark-title');
 const categories=[['Nightlife','Vida nocturna','The city clocks out. We clock in.','La ciudad sale del trabajo. Nosotros salimos a explorar.','Bars, dance floors, live music, and the places worth staying up for.','Bares, baile, música en vivo y lugares que merecen una noche larga.'],['Nighttime adventures','Aventuras nocturnas','Less daylight. More possibility.','Menos luz. Más posibilidades.','Stargazing, night walks, late-night food, and events after sunset.','Estrellas, paseos, comida de madrugada y eventos después del atardecer.'],['Lost Footage','Lost Footage','Some stories miss the final cut.','Algunas historias quedan fuera del montaje.','The candid moments, late-night conversations, and grown-up side of getting lost.','Momentos espontáneos, conversaciones nocturnas y el lado adulto de perderse.']];
 let category=0;
 const nightPicks=[
  ['The Ripple Room','183 Bowery, Manhattan','bar','https://www.google.com/maps/search/?api=1&query=The+Ripple+Room+183+Bowery+New+York','NYC'],
  ['Abracadabra','English Harbour, Antigua','club','https://www.visitantiguabarbuda.com/culinary/abracadabra-antigua/','AG'],
  ['Shirley Heights','English Harbour, Antigua','sunset','https://www.visitantiguabarbuda.com/things-to-do/shirley-heights-lookout/','AG'],
  ['Loose Cannon','Galleon Beach, Antigua','sunset','https://www.loosecannonbeachbar.com/','AG'],
  ['VYCE','St. John’s, Antigua','club','https://www.antiguasearch.com/listing/vyce-sports-bar-and-lounge','AG'],
  ['Mr Liquor','Santiago, Dominican Republic','bar','https://mrliquorrd.com/','DR'],
  ['La Ciguapa','Santiago, Dominican Republic','perreo','https://visitsantiago.do/lugar/la-ciguapa/','DR'],
  ['Galipote Afterwork','Santiago, Dominican Republic','bar','https://www.instagram.com/galipoterd/','DR'],
  ['Lovera','Santiago, Dominican Republic','club','https://www.hotellovera.com/en/lovera-discotec-en','DR'],
  ['Cielo Rooftop','AC Hotel / Santiago, Dominican Republic','rooftop','https://www.marriott.com/en-us/dining/restaurant-bar/stiac-ac-hotel-santiago-de-los-caballeros/7324880-cielo-rooftop.mi','DR'],
  ['Mijani The Club','La Placita, Santurce','club','https://www.discoverpuertorico.com/article/guide-to-la-placita-restaurants-bars-nightlife','SJ','La Placita / Top 5 to explore'],
  ['Club Vibra','La Placita, Santurce','perreo','https://www.discoverpuertorico.com/article/guide-to-la-placita-restaurants-bars-nightlife','SJ','La Placita / Top 5 to explore'],
  ['Aguardiente','La Placita, Santurce','club','https://www.discoverpuertorico.com/article/best-places-to-experience-nightlife-san-juan','SJ','La Placita / Top 5 to explore'],
  ['Garabatos','La Placita, Santurce','club','https://www.discoverpuertorico.com/article/best-places-to-experience-nightlife-san-juan','SJ','La Placita / Top 5 to explore'],
  ['Bar El Rubí','La Placita, Santurce','bar','https://www.discoverpuertorico.com/article/best-places-to-experience-nightlife-san-juan','SJ','La Placita / Top 5 to explore'],
  ['Distrito T-Mobile','Convention District, San Juan','district','https://www.distritot-mobile.com/','SJ','Beyond La Placita'],
  ['La 39','La Perla, Old San Juan','bar','https://www.discoverpuertorico.com/article/visiting-la-perla-neighborhood-old-san-juan','SJ','La Perla / The bar pick'],
  ['Pianos','Lower East Side, Manhattan','club','https://pianosnyc.com/','NYC'],
  ['Marquee','Chelsea, Manhattan','club','https://taogroup.com/venues/marquee-new-york/','NYC'],
  ['Lost in Paradise','Long Island City, Queens','perreo','https://www.lostinparadiserooftop.com/','NYC'],
  ['Republic Latin Fusion','Williamsburg, Brooklyn','perreo','https://republiclatinfusion.com/','NYC'],
  ['Dramma','Times Square, Manhattan','club','https://1604broadway.com/','NYC'],
  ['The Delancey Rooftop','Lower East Side, Manhattan','rooftop','https://thedelancey.com/','NYC'],
  ['Fat Taco','Hoboken, New Jersey','perreo','https://www.fattacohoboken.com/','NJ'],
  ['Perreo on the Pier','Watermark / Pier 15, South Street','perreo','https://www.eventbrite.com/e/perreo-on-the-pier-open-air-latin-reggaeton-dance-party-nyc-tickets-1338926006729','NYC'],
  ['BarCode','Elizabeth, New Jersey','perreo','https://barcodenj.com/','NJ']
 ];
 function renderNightlife(){
  const room=dark.querySelector('.after-dark-room');
  room.innerHTML=`<span class="night-room-number">01 / ${t('THE NIGHT SHIFT','EL TURNO DE NOCHE')}</span><h3>${t('Miss the bedtime. Keep the story.','Pierde el sueño. Quédate con la historia.')}</h3><p>${t('Different cities. Later nights. A few good reasons to stay lost a little longer.','Otras ciudades. Noches más largas. Razones para seguir perdidos un rato más.')}</p><label class="night-city-label">${t('Choose your city','Elige tu ciudad')}<select class="night-city"><option value="NYC">New York City</option><option value="NJ">New Jersey</option><option value="AG">Antigua</option><option value="DR">Dominican Republic / Santiago</option><option value="SJ">San Juan / Puerto Rico</option><option>Buenos Aires</option><option>Mendoza</option><option>Santiago</option><option>La Paz</option></select></label><div class="night-vibe-filters" aria-label="${t('Nightlife vibe','Tipo de noche')}"><button type="button" data-vibe="all" aria-pressed="true">${t('All nights','Todas')}</button><button type="button" data-vibe="perreo" aria-pressed="false">Perreo / Reggaeton</button><button type="button" data-vibe="rooftop" aria-pressed="false">${t('Rooftops','Azoteas')}</button><button type="button" data-vibe="club" aria-pressed="false">${t('Dance floors','Pistas de baile')}</button></div><div class="night-venues" aria-live="polite"></div><p class="night-program-note">${t('The venue is the starting point. Check its current lineup for the night, music, and entry details.','El lugar es el punto de partida. Consulta su programación para la música y los detalles de entrada.')}</p>`;
  let vibe='all';const city=room.querySelector('select');
  function draw(){const picks=nightPicks.filter(p=>(p[4]===city.value)&&(vibe==='all'||p[2]===vibe||(vibe==='rooftop'&&p[0]==='Lost in Paradise')));room.querySelector('.night-venues').innerHTML=picks.length?picks.map((p,index)=>`${city.value==='SJ'&&p[5]!==picks[index-1]?.[5]?`<h4 class="night-area-heading">${p[5]}</h4>`:''}<a class="night-venue" href="${p[3]}" target="_blank" rel="noopener noreferrer"><span class="night-venue-symbol" aria-hidden="true">${p[2]==='perreo'?'♫':p[2]==='rooftop'?'☾':'◈'}</span><small>${p[1]}</small><h4>${p[0]}</h4><span class="night-venue-tag">${p[2]==='perreo'?'PERREO / REGGAETON':p[2]==='rooftop'?t('ROOFTOP','AZOTEA'):p[2]==='bar'?t('BAR / LIVE MUSIC','BAR / MÚSICA EN VIVO'):p[2]==='sunset'?t('SUNSET / OPEN AIR','ATARDECER / AL AIRE LIBRE'):p[2]==='district'?t('ENTERTAINMENT DISTRICT','DISTRITO DE ENTRETENIMIENTO'):t('DANCE FLOOR','PISTA DE BAILE')}</span><span class="night-venue-link">${t('Explore the night','Explora la noche')} ↗</span></a>`).join(''):`<div class="night-empty"><span aria-hidden="true">☾</span><strong>${t('This part of the night is still unwritten.','Esta noche todavía está por escribir.')}</strong><p>${t('More places will land here as we explore. Try another city or vibe.','Aquí llegarán más lugares. Prueba otra ciudad o ambiente.')}</p></div>`;}
  city.onchange=draw;room.querySelectorAll('[data-vibe]').forEach(b=>b.onclick=()=>{vibe=b.dataset.vibe;room.querySelectorAll('[data-vibe]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));draw();});draw();
 }

 function renderAdventures(){
  const room=dark.querySelector('.after-dark-room');
  room.innerHTML=`<span class="night-room-number">02 / NEW YORK CITY</span><h3>${t('The city stays up. So can the adventure.','La ciudad sigue despierta. La aventura también.')}</h3><p>${t('Jazz, a little salsa, skyline miles, and the occasional look up.','Jazz, un poco de salsa, kilómetros de skyline y una mirada al cielo.')}</p><div class="night-vibe-filters" aria-label="${t('Choose an adventure','Elige una aventura')}">${[['all',t('All adventures','Todas')],['music',t('Music & dance','Música y baile')],['games',t('Game night','Juegos')],['outdoors',t('Under the sky','Bajo el cielo')],['food',t('Evening bites','Algo de comer')]].map(([key,label])=>`<button type="button" data-adventure="${key}" aria-pressed="${key==='all'}">${label}</button>`).join('')}</div><div class="night-venues adventure-venues" aria-live="polite"></div>`;
  function draw(filter){room.querySelector('.adventure-venues').innerHTML=window.LPNightAdventures.filter(p=>filter==='all'||p.type===filter).map(p=>`<a class="night-venue night-adventure" href="${p.url}" target="_blank" rel="noopener noreferrer"><span class="night-venue-symbol" aria-hidden="true">${p.type==='music'?'♫':p.type==='outdoors'?'✦':p.type==='games'?'⚄':'☾'}</span><small>${p.place}</small><h4>${p.name}</h4><p class="adventure-hook">${t(...p.copy)}</p><p class="adventure-detail">${t(...p.detail)}</p><span class="night-venue-link">${t('Plan the detour','Planea el desvío')} ↗</span></a>`).join('');}
  room.querySelectorAll('[data-adventure]').forEach(b=>b.onclick=()=>{room.querySelectorAll('[data-adventure]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));draw(b.dataset.adventure);});draw('all');
 }
 function renderDark(){
  dark.innerHTML=`<button class="orbit-close" type="button" aria-label="${t('Return to the sky','Volver al cielo')}">×</button><div class="underworld-header"><span class="secret-coordinate">L&amp;P / ${t('YOU FOUND THE OTHER SIDE','ENCONTRASTE EL OTRO LADO')}</span><div class="underworld-moon" aria-hidden="true">☾</div><h2 id="after-dark-title">Lost <em>After Dark</em></h2><p>${t('Good nights rarely follow the itinerary.','Las mejores noches rara vez siguen el itinerario.')}</p><span class="secret-unlocked">${t('OFF THE ITINERARY · AFTER HOURS','FUERA DEL ITINERARIO · DE NOCHE')}</span></div><nav class="after-dark-tabs" aria-label="${t('Explore after dark','Explorar de noche')}">${categories.map((c,i)=>`<button type="button" data-night="${i}" aria-pressed="${category===i}">${t(c[0],c[1])}</button>`).join('')}</nav><section class="after-dark-room" aria-live="polite"></section><footer class="underworld-footer">${t('You weren’t lost. You were looking in the right shadows.','No estabas perdido. Buscabas en las sombras correctas.')}</footer>`;
  dark.querySelector('.orbit-close').onclick=()=>dark.close();
  dark.querySelectorAll('[data-night]').forEach(b=>b.onclick=()=>{category=Number(b.dataset.night);dark.querySelectorAll('[data-night]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));renderRoom();});renderRoom();
 }
 function renderRoom(){if(category===0){renderNightlife();return;}if(category===1){renderAdventures();return;}const c=categories[category];dark.querySelector('.after-dark-room').innerHTML=`<span class="night-room-number">0${category+1} / ${category===2?t('THE PRIVATE CUT · MATURE AUDIENCES','EL OTRO MONTAJE · PÚBLICO ADULTO'):t('FIELD NOTES AFTER SUNSET','NOTAS DESPUÉS DEL ATARDECER')}</span><h3>${t(c[2],c[3])}</h3><p>${t(c[4],c[5])}</p>${category!==2?`<label class="night-city-label">${t('A different city. A different night.','Otra ciudad. Otra noche.')}<select class="night-city"><option>Buenos Aires</option><option>Mendoza</option><option>Santiago</option><option>La Paz</option><option>New York</option></select></label>`:''}<div class="night-empty"><span aria-hidden="true">${category===2?'▤':category===1?'✦':'◒'}</span><strong class="night-empty-title"></strong><p>${category===2?t('Our first Lost Footage drop is still in the vault. Real clips and stories will land here when we’re ready to share them.','El primer Lost Footage sigue en la bóveda. Aquí llegarán nuestros videos e historias cuando estén listos.'):t('Our own recommendations and experiences will appear here after we explore. No borrowed favorites. No invented nights.','Nuestras recomendaciones y experiencias llegarán después de explorar. Sin favoritos prestados ni noches inventadas.')}</p></div>`;const select=dark.querySelector('.night-city');const update=()=>{dark.querySelector('.night-empty-title').textContent=category===2?t('The vault is waiting.','La bóveda espera.'):(select.value+' / '+t('Field notes coming soon','Próximamente'));};if(select)select.onchange=update;update();}
 let darkEntranceTimer;
 moon.onclick=()=>{
  renderDark();dark.classList.remove('after-dark-entering');
  if(!matchMedia('(prefers-reduced-motion: reduce)').matches)dark.classList.add('after-dark-entering');
  dark.showModal();dark.scrollTop=0;
  clearTimeout(darkEntranceTimer);
  darkEntranceTimer=setTimeout(()=>dark.classList.remove('after-dark-entering'),3000);
 };
 dark.addEventListener('close',()=>{clearTimeout(darkEntranceTimer);dark.classList.remove('after-dark-entering');moon.focus({preventScroll:true});});
 const next=modal('where-next');next.setAttribute('aria-labelledby','where-next-title');
 const ship=document.createElement('button');ship.type='button';ship.className='where-next-ship';ship.setAttribute('aria-haspopup','dialog');ship.setAttribute('aria-controls','where-next');
 ship.innerHTML='<svg viewBox="0 0 70 55" aria-hidden="true"><path d="M24 26q2-21 11-21t11 21" fill="#9fd4d6" stroke="#315b67" stroke-width="2"/><path d="M8 31q27-19 54 0-27 23-54 0Z" fill="#dfd9c6" stroke="#315b67" stroke-width="2"/><ellipse cx="35" cy="30" rx="27" ry="7" fill="#819eaa" stroke="#315b67" stroke-width="2"/><path d="m24 43-5 7m16-6v8m11-9 5 7" stroke="#d5b36e" stroke-width="2"/><g fill="#ffe5a1"><circle cx="20" cy="30" r="2"/><circle cx="35" cy="32" r="2"/><circle cx="50" cy="30" r="2"/></g></svg><span></span>';
 window.LPDestinations={mount(container=document){const dock=container.querySelector('[data-destination-ufo]');if(dock)dock.append(ship);}};
 window.LPDestinations.mount();
 const mapShip=ship.cloneNode(true);document.querySelector('.gps-expanded-screen .gps-compass-dock')?.append(mapShip);let activeShip=ship;
 let pending=false,submissionId=null;
 next.innerHTML=`<button class="orbit-close" type="button" aria-label="${t('Close suggestions','Cerrar sugerencias')}">×</button><span class="secret-coordinate">L&amp;P / ${t('MISSION CONTROL','CONTROL DE MISIÓN')}</span><h2 id="where-next-title">${t('Where to next?','¿A dónde vamos?')}</h2><p>${t('Give our questionable sense of direction a new destination.','Dale un nuevo destino a nuestro dudoso sentido de orientación.')}</p><form class="destination-form"><div class="destination-fields"><label>${t('Country','País')}<input name="country" required maxlength="40" autocomplete="country-name"></label><label>${t('City','Ciudad')}<input name="city" required maxlength="60" autocomplete="address-level2"></label></div><label>${t('Why should we get lost there?','¿Por qué deberíamos perdernos allí?')}<textarea name="reason" rows="3" maxlength="500" placeholder="${t('A place, an experience, or simply a very good hunch.','Un lugar, una experiencia o una buena corazonada.')}"></textarea></label><label class="destination-trap" aria-hidden="true">Website<input name="website" tabindex="-1" autocomplete="off"></label><small>${t('Your destination and note will appear on this shared list.','Tu destino y nota aparecerán en esta lista compartida.')}</small><button type="submit">${t('Send the coordinates','Enviar las coordenadas')} ↗</button></form><p class="destination-status" role="status"></p><div class="destination-list"></div><button type="button" class="destination-refresh">${t('Refresh destinations','Actualizar destinos')} ↻</button>`;
 const form=next.querySelector('form'),status=next.querySelector('.destination-status'),submit=form.querySelector('[type=submit]');
 next.querySelector('.orbit-close').onclick=()=>next.close();next.addEventListener('close',()=>activeShip.focus({preventScroll:true}));
 async function request(options){
  const unavailable=()=>new Error(t('Destination suggestions are temporarily unavailable. Please try again shortly.','Las sugerencias no están disponibles por ahora. Inténtalo de nuevo en un momento.'));
  let r;try{r=await fetch('/api/destinations',{...options,signal:AbortSignal.timeout(12000)});}catch{throw unavailable();}
  if(r.status===429)throw new Error(t('Let this destination land. Try again in a minute.','Espera un minuto antes de enviar otro destino.'));
  if(!r.ok)throw unavailable();
  let data;try{data=await r.json();}catch{throw unavailable();}
  if(!data||typeof data!=='object'||(options?.method==='POST'?!data.story:!Array.isArray(data.stories)))throw unavailable();
  return data;
 }
 function cards(items){const list=next.querySelector('.destination-list');list.replaceChildren();if(!items.length){list.textContent=t('Uncharted territory. Leave the first coordinates.','Territorio nuevo. Deja las primeras coordenadas.');return;}items.forEach(item=>{const card=document.createElement('article'),title=document.createElement('strong'),note=document.createElement('p');title.textContent=item.place+', '+item.name;note.textContent=item.story;card.append(title,note);list.append(card);});}
 let revision=0;
 async function refresh(){const version=revision;try{const data=await request();if(version===revision){cards(data.stories);status.textContent='';}}catch(e){if(version===revision)status.textContent=e.message;}}
 ship.onclick=mapShip.onclick=event=>{activeShip=event.currentTarget;next.showModal();refresh();};next.querySelector('.destination-refresh').onclick=refresh;
 form.addEventListener('input',()=>submissionId=null);
 form.addEventListener('submit',async e=>{e.preventDefault();if(pending||!form.reportValidity())return;const reason=form.elements.reason.value.trim();if(reason.split(/\s+/u).length>100){status.textContent=t('Keep your note to 100 words.','Máximo 100 palabras.');return;}pending=true;submit.disabled=true;submissionId??=crypto.randomUUID();status.textContent=t('Sending coordinates…','Enviando coordenadas…');try{await request({method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:submissionId,name:form.elements.country.value,place:form.elements.city.value,story:reason||t('A new place to get lost.','Un nuevo lugar para perdernos.'),website:form.elements.website.value})});revision++;form.reset();submissionId=null;await refresh();status.textContent=t('Coordinates received. Officially on our radar.','Coordenadas recibidas. Ya está en nuestro radar.');}catch(error){status.textContent=error.message;}finally{pending=false;submit.disabled=false;}});
 function labels(){moon.setAttribute('aria-label',t('Discover Lost After Dark','Descubre Lost After Dark'));moon.title=t('Lost After Dark','Lost After Dark');ship.querySelector('span').textContent=t('Where to next?','¿A dónde vamos?');ship.setAttribute('aria-label',t('Suggest where we should travel next','Sugiere nuestro próximo destino'));}
 const labelBoth=()=>{labels();mapShip.querySelector('span').textContent=ship.querySelector('span').textContent;mapShip.setAttribute('aria-label',ship.getAttribute('aria-label'));};
 labelBoth();document.addEventListener('lp:languagechange',()=>{labelBoth();if(dark.open)renderDark();});
})();




