/* Uncommissioned previews use personal photographs, never fabricated endorsements. */
(() => {
 const esc = value => String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const stingrayBadge = language => '<a class="stingray-badge" href="https://www.stingraycity.com/" target="_blank" rel="noopener noreferrer" aria-label="'+(language==='es'?'Visita Stingray City (sitio externo)':'Visit Stingray City (external website)')+'"><img src="assets/stingray-city-logo.png" alt="Stingray City Antigua" width="90" height="53" loading="lazy"></a>';
 function render(language,kind,choice){
  const es=language==='es',t=(en,translation)=>es?translation:en,partnership=Number(kind)===2;
  choice=choice||(partnership?'dji':'instagram');
  const options=partnership?[['dji','DJI'],['airalo','Airalo'],['patagonia','Patagonia']]:[['instagram','Instagram'],['youtube','YouTube'],['tiktok','TikTok']];
  const brand=options.find(item=>item[0]===choice)?.[1]||'DJI';
  const caption=partnership?(choice==='airalo'?t('New place. Same connection.','Nuevo lugar. La misma conexión.'):choice==='patagonia'?t('Pack less. Go further.','Lleva menos. Llega más lejos.'):t('Keep the moment. Share the journey.','Guarda el momento. Comparte el viaje.')):t('A little lost. A lot to discover.','Un poco perdidos. Mucho por descubrir.');
  const photo=partnership?(choice==='patagonia'?'assets/travel-previews/8cc54ccb34d76714.jpg':'assets/travel-previews/ad79ef0f076d-cover.jpg'):'assets/travel-previews/6491edeb4000-cover.jpg';
  const alt=partnership?(choice==='patagonia'?t('Mountain meadow in Colombia, personal travel photo','Pradera de montaña en Colombia, foto personal'):t('John in Milan, personal travel photo','John en Milán, foto personal')):t('John with a stingray in Antigua','John con una mantarraya en Antigua');
  const account='<div class="studio-account"><img src="assets/2EA6D4BC-C72D-4AC1-BC61-01DF255EEA1E_1_105_c.jpeg" alt="" width="30" height="30"><span><b>lostandperdido</b><small>'+ (partnership?'L&P × '+brand+' · '+t('Concept','Concepto'):'Stingray City Antigua · '+t('Concept','Concepto'))+'</small></span></div>';
  const disclosure=partnership?t('Uncommissioned concept · no existing partnership or endorsement','Concepto no contratado · sin alianza ni respaldo de la marca'):t('Personal excursion · illustrative collaboration concept, not a sponsored post','Excursión personal · concepto ilustrativo de colaboración, no publicación patrocinada');
  const product=choice==='dji'?'<img class="studio-product" src="assets/dji-pocket-3-illustration.svg" alt="DJI Pocket 3 illustration">':choice==='airalo'?'<div class="studio-esim-card"><span>eSIM</span><b>ARG → CHL → BOL</b><small>'+t('Stay connected.','Sigue conectado.')+'</small><span aria-hidden="true">▂ ▄ ▆ █</span></div>':'<div class="studio-jacket"><svg viewBox="0 0 90 100" role="img" aria-label="'+t('Illustrative outdoor jacket','Chaqueta de exterior ilustrativa')+'"><path d="m29 14 8-9h16l8 9 17 7 10 43-15 5-9-29v52H26V40l-9 29-15-5 10-43Z" fill="#be5b35" stroke="#542f27" stroke-width="2"/><path d="m29 14 16 12 16-12M45 26v65M29 55h10m13 0h10" fill="none" stroke="#f3dbc5" stroke-width="2"/></svg><small>'+t('Gear concept','Concepto de equipo')+'</small></div>';
  const visual='<div class="studio-post-visual"><img class="studio-scene" src="'+photo+'" alt="'+esc(alt)+'" loading="lazy">'+(partnership?'<div class="studio-brand-lockup"><b>'+brand+'</b><span>× LOST &amp; PERDIDO</span></div>'+product+'<p class="studio-post-headline">'+esc(caption)+'</p>':stingrayBadge(language))+(choice==='youtube'?'<div class="studio-video-controls" aria-hidden="true"><span>▶</span><span>0:00 / 8:24</span><span>⚙ ⛶</span><i></i></div>':'')+(choice==='tiktok'?'<div class="studio-tiktok-tools" aria-hidden="true"><span>◉</span><span>♥</span><span>●</span><span>↗</span></div><div class="studio-tiktok-overlay"><b>@lostandperdido</b><p>'+esc(caption)+'</p><small>♫ '+t('Original sound · Lost & Perdido','Sonido original · Lost & Perdido')+'</small></div>':'')+'</div>';
  const youtube=choice==='youtube',tiktok=choice==='tiktok';
  const platformHeader=tiktok?'<div class="studio-tiktok-tabs" aria-hidden="true">'+t('Following','Siguiendo')+' <b>'+t('For You','Para ti')+'</b> ⌕</div>':'<div class="studio-platform-bar"><strong>'+(youtube?'<span class="youtube-mark">▶</span> YouTube':'Instagram')+'</strong><span aria-hidden="true">'+(youtube?'⌕ ⋮':'＋ ♡')+'</span></div>';
  const body=tiktok?visual:youtube?visual+'<div class="studio-youtube-title"><b>'+t('Stingray City, Antigua | Getting lost with us','Stingray City, Antigua | Perdiéndonos juntos')+'</b><small>'+t('Episode preview · Personal excursion','Vista previa · Excursión personal')+'</small></div>'+account+'<div class="studio-youtube-actions" aria-hidden="true">♡ '+t('Like','Me gusta')+'　↗ '+t('Share','Compartir')+'　⊕</div>':account+visual+'<div class="studio-post-actions" aria-hidden="true">♡ ◯ ⤴ <span>♧</span></div>';
  return '<div class="modern-phone-stage" data-studio-kind="'+kind+'" data-studio-language="'+language+'"><div class="studio-choice-row" role="group" aria-label="'+t('Choose a preview','Elige una vista previa')+'">'+options.map(([id,label])=>'<button type="button" data-phone-choice="'+id+'" aria-pressed="'+(choice===id)+'">'+label+'</button>').join('')+'</div><div class="studio-phone studio-platform-'+choice+'"><div class="studio-phone-status" aria-hidden="true"><span>9:41</span><i></i><span>▮▮▮ ▰</span></div>'+platformHeader+body+(!tiktok?'<div class="studio-caption">'+(!youtube?'<strong>lostandperdido</strong> '+esc(caption):'')+'<small>'+disclosure+'</small></div>':'')+'<div class="studio-phone-nav" aria-hidden="true">'+(tiktok?'⌂　♧　⊞　▣　♙':youtube?'⌂　▷　⊕　▣　◉':'⌂　⌕　⊞　▷　◉')+'</div></div>'+(tiktok?'<small class="studio-outside-disclosure">'+disclosure+'</small>':'')+'<p class="studio-preview-note">'+(partnership?t('Imagine your brand in the next chapter.','Imagina tu marca en el próximo capítulo.'):t('A story shaped for the way people watch.','Una historia pensada para cómo vemos el mundo.'))+'</p></div>';
 }
 window.LPStudio={render,stingrayBadge};
 document.addEventListener('click',event=>{const button=event.target.closest('[data-phone-choice]');if(!button)return;const stage=button.closest('.modern-phone-stage'),holder=document.createElement('div');holder.innerHTML=render(stage.dataset.studioLanguage,stage.dataset.studioKind,button.dataset.phoneChoice);const replacement=holder.firstElementChild;stage.replaceWith(replacement);replacement.querySelector('[data-phone-choice="'+button.dataset.phoneChoice+'"]').focus({preventScroll:true});});
})();
(()=>{const screen=document.querySelector('.gps-expanded-screen');if(!screen)return;const dock=document.createElement('div');dock.className='gps-compass-dock';dock.innerHTML='<p role="status"></p><button type="button" aria-label="Find a little direction"><svg viewBox="0 0 80 80" aria-hidden="true"><circle cx="40" cy="40" r="36"/><circle cx="40" cy="40" r="27" stroke-dasharray="1 5"/><text x="37" y="13">N</text><text x="67" y="43">E</text><text x="37" y="74">S</text><text x="7" y="43">W</text><g class="compass-needle"><path d="m40 18-7 23 7-4 7 4Z" fill="#b84435" stroke="none"/><path d="m40 62-7-23 7 4 7-4Z" fill="#355d70" stroke="none"/></g><circle cx="40" cy="40" r="3" fill="#e8d9b1"/></svg></button>';screen.insertBefore(dock,screen.querySelector('.gps-map-status'));let n=-1;const prompts=[['Ask a local where they love to eat.','Pregúntale a alguien de aquí dónde le encanta comer.'],['Learn one phrase. Start one conversation.','Aprende una frase. Empieza una conversación.'],['Take the scenic way. Leave room for surprise.','Elige el camino bonito. Deja espacio para la sorpresa.']];const update=()=>{const es=document.documentElement.lang==='es';dock.querySelector('button').setAttribute('aria-label',es?'Encuentra un poco de rumbo':'Find a little direction');if(n>=0)dock.querySelector('p').textContent=prompts[n][es?1:0];};dock.querySelector('button').addEventListener('click',()=>{n=(n+1)%prompts.length;update();});document.addEventListener('lp:languagechange',update);update();})();
