/* Our own picks, with artwork linked back to the artists and shows. */
(() => {
 const data={"artists": [{"key": "ozuna", "name": "Ozuna", "url": "https://open.spotify.com/artist/1i8SpTcr7yvPOmcqrbnVXY"}, {"key": "omega", "name": "Omega", "url": "https://open.spotify.com/artist/1UjxAZqzphB1tsMb1aWBj0"}, {"key": "bad-bunny", "name": "Bad Bunny", "url": "https://open.spotify.com/artist/4q3ewBCX7sLwd24euuV69X"}, {"key": "el-alfa", "name": "El Alfa", "url": "https://open.spotify.com/artist/2oQX8QiMXOyuqbcZEFsZfm"}, {"key": "anthony-santos", "name": "Anthony Santos", "url": "https://open.spotify.com/artist/06TVTkMAOR935MhkjX0i2A"}, {"key": "fran-aliss", "name": "Fran Aliss", "url": "https://open.spotify.com/artist/3PlgEHWfJplE2qFIVCls6E"}, {"key": "feel-trip", "name": "feel trip.", "url": "https://open.spotify.com/artist/7ysdcHcrr06qQJ1BL0dKVU"}], "songs": [{"key": "mi-buena-suerte", "name": "mi buena suerte.", "artist": "feel trip.", "url": "https://open.spotify.com/track/6xVXJynT4L6aPmbI6Rzw5M"}, {"key": "hipnotizado", "name": "Hipnotizado", "artist": "Fran Aliss", "url": "https://open.spotify.com/track/2KGSIsAOIyXltuVeOThuch"}, {"key": "omega-song", "name": "Tu No Tá Pa’ Mi", "artist": "Omega", "url": "https://open.spotify.com/track/6n5AS39NnVJiilJmeNy6jT"}], "shows": [{"key": "icarly", "name": "iCarly", "url": "https://www.tvmaze.com/shows/808/icarly"}, {"key": "spongebob", "name": "SpongeBob SquarePants", "url": "https://www.tvmaze.com/shows/713/spongebob-squarepants"}, {"key": "the-office", "name": "The Office", "url": "https://www.tvmaze.com/shows/526/the-office"}]};
 const opener=document.querySelector('.top-picks-launch');
 const dialog=document.createElement('dialog');dialog.id='lp-top-picks';dialog.className='top-picks-dialog';dialog.setAttribute('aria-labelledby','top-picks-title');document.body.append(dialog);
 const esc=value=>String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 let filter='all';
 const t=(en,es)=>document.documentElement.lang==='es'?es:en;
 const photo=(key,name,cls='')=>`<img class="${cls}" src="assets/top-picks/${key}.jpg" alt="${esc(name)}" loading="lazy" decoding="async">`;
 function content(){
  const songs=`<section class="picks-section picks-songs"><header><span>01 / ON REPEAT</span><h3>${t('The road-trip soundtrack','La banda sonora del viaje')}</h3></header><div class="picks-track-list">${data.songs.map((song,i)=>`<a class="picks-track" href="${song.url}" target="_blank" rel="noopener noreferrer" aria-label="${esc(song.name+' — '+t('Listen on Spotify','Escuchar en Spotify'))}"><span class="picks-track-number">0${i+1}</span>${photo(song.key,song.name+' / '+song.artist)}<span><strong>${esc(song.name)}</strong><small>${esc(song.artist)}</small></span><span class="picks-play" aria-hidden="true">↗</span></a>`).join('')}</div><p class="picks-small">${t('Listen on Spotify ↗','Escuchar en Spotify ↗')}</p></section>`;
  const artists=`<section class="picks-section picks-artists"><header><span>02 / OUR ROTATION</span><h3>${t('Always in the queue','Siempre en la fila')}</h3></header><div class="picks-artist-grid">${data.artists.map((artist,i)=>`<a class="picks-artist" style="--pick-hue:${[315,30,145,265,5,205,60][i]}" href="${artist.url}" target="_blank" rel="noopener noreferrer">${photo(artist.key,artist.name)}<strong>${esc(artist.name)}</strong><small>Spotify ↗</small></a>`).join('')}</div></section>`;
  const shows=`<section class="picks-section picks-shows"><header><span>03 / ONE MORE EPISODE</span><h3>${t('Comfort shows. Cero shame.','Series de confort. Zero shame.')}</h3></header><div class="picks-show-grid">${data.shows.map((show,i)=>`<a class="picks-show" href="${show.url}" target="_blank" rel="noopener noreferrer">${photo(show.key,show.name)}<span><small>0${i+1} / ${t('OUR FAVORITES','FAVORITAS')}</small><strong>${esc(show.name)}</strong></span></a>`).join('')}</div><small class="picks-small">${t('Show details & artwork: TVmaze ↗','Detalles e imágenes de las series: TVmaze ↗')}</small></section>`;
  return (filter==='all'||filter==='songs'?songs:'')+(filter==='all'||filter==='artists'?artists:'')+(filter==='all'||filter==='shows'?shows:'');
 }
 function render(){
  opener.setAttribute('aria-label',t('Open Lost & Perdido’s Top Picks','Abrir los Top Picks de Lost & Perdido'));
  dialog.innerHTML=`<div class="picks-topbar"><span>LOST &amp; PERDIDO / PERSONAL ROTATION</span><button type="button" class="picks-close" aria-label="${t('Close Top Picks','Cerrar Top Picks')}">×</button></div><header class="picks-hero"><div class="picks-cover" aria-hidden="true">${['ozuna','bad-bunny','fran-aliss','feel-trip'].map(key=>photo(key,'')).join('')}<span>LOST &amp;<br>PERDIDO’S<br>TOP PICKS ✦</span></div><div><p class="picks-eyebrow">${t('CURATED BY JOHN & MATEO','ELEGIDO POR JOHN Y MATEO')}</p><h2 id="top-picks-title"><span class="picks-full-brand">Lost &amp; Perdido’s</span><br><em>Top Picks.</em></h2><p>${t('Good music. Familiar faces. Un poquito de todo.','Buena música. Caras conocidas. A little bit of everything.')}</p><span class="picks-count">3 ${t('songs','canciones')} · 7 ${t('artists','artistas')} · 3 ${t('shows','series')}</span></div></header><nav class="picks-filters" aria-label="${t('Browse our picks','Explora nuestros favoritos')}">${[['all',t('Everything','Todo')],['songs',t('Songs','Canciones')],['artists',t('Artists','Artistas')],['shows',t('TV shows','Series')]].map(([key,label])=>`<button type="button" data-picks-filter="${key}" aria-pressed="${filter===key}">${label}</button>`).join('')}</nav><div class="picks-content">${content()}</div><footer class="picks-footer">LOST &amp; PERDIDO · ${t('A little lost. Great taste.','Un poco perdidos. Mucho gusto.')}</footer>`;
 }
 dialog.addEventListener('click',event=>{
  if(event.target.closest('.picks-close')){dialog.close();return;}
  const choice=event.target.closest('[data-picks-filter]');if(!choice)return;
  filter=choice.dataset.picksFilter;
  dialog.querySelectorAll('[data-picks-filter]').forEach(button=>button.setAttribute('aria-pressed',String(button===choice)));
  dialog.querySelector('.picks-content').innerHTML=content();
 });
 opener.addEventListener('click',()=>{render();dialog.showModal();dialog.scrollTop=0;dialog.querySelector('.picks-close').focus();});
 dialog.addEventListener('close',()=>opener.focus({preventScroll:true}));
 document.addEventListener('lp:languagechange',()=>{if(dialog.open)render();else opener.setAttribute('aria-label',t('Open Lost & Perdido’s Top Picks','Abrir los Top Picks de Lost & Perdido'));});
})();
